name: Build and run Pulsar4X tests on Windows Server 2022

on:
  push:
    branches: [ AddGithubActions ]
  pull_request:
    branches: [ AddGithubActions ]

jobs:
  use-actions:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: build
        shell: pwsh
        run: |
          cd Pulsar4X
          dotnet restore "Pulsar4X.sln"
          dotnet build --no-restore
          
      - name: tests
        shell: pwsh
        run: |
          dotnet test --no-restore